apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  prefix: {{ .Values.lte.prefix }}
  identity: {{ .Values.lte.identity }}
  realm: {{ .Values.lte.realm }}
  dbFqdn: {{ .Values.lte.dbFqdn }}
  opKey: {{ .Values.lte.opKey | quote }}
  roaming: {{ .Values.lte.roaming | quote }}
  apn1: {{ .Values.lte.apn1 }}
  apn2: {{ .Values.lte.apn2 }}
  lteK: {{ .Values.lte.lteK | quote }}
  imsi: {{ .Values.lte.imsi | quote }}
  numSubscribers: {{ .Values.lte.numSubscribers | quote }}
  dbName: {{ .Values.lte.dbName }}
  dbUser: {{ .Values.lte.dbUser }}
  dbPassword: {{ .Values.lte.dbPassword }}
  
