apiVersion: v2
name: oai-spgwu-tiny
description: A Helm chart for SPGWU-TINY network function

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: onap-0.1.0

# TODO
#dependencies:
#- name: oai-spgwc
#  version: "0.1.0"
#  repository: "file://..."

keywords:
  - Core Network
  - EPC
  - 4G
  - Edge
  - SPGW
  - SPGW-U
  - CUPS

sources:
  - https://github.com/OPENAIRINTERFACE/openair-spgwu-tiny
  - https://github.com/OPENAIRINTERFACE/openair-k8s

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org
    # GITHUB account
  - name: lionelgo
    email: lionel.gauthier@eurecom.fr
